spec:
  template:
    spec:
      containers:
      - name: bank-app
        image: manaswinik10/bank-app:v3  # <-- you will build this next
        env:
        - name: DATABASE_URL
          value: "sqlite:////data/app.db"
        - name: SEED_ON_START
          value: "true"     # after first successful deploy -> change to "false"
        volumeMounts:
        - name: bank-data
          mountPath: /data
      volumes:
      - name: bank-data
        emptyDir: {}        # survives container restarts
        env:
         - name: SEED_DEMO
           value: "false"



